### ISSUE TITLE
Please add spectrum support.

### ISSUE THREAD

**Issue by skyleet** [KudProject/kernel_xiaomi_msm8953-3.18#2]

**Comment by raphielscape** [comment]
Why tho

**Comment by skyleet** [comment]
I keep it as battery mostly and gaming/performance for some time. :)

**Comment by raphielscape** [comment]
Why you don't using KA instead?

**Comment by skyleet** [comment]
I think it's time to move to KA. I like spectrum because it has QS tile. Easy to toggle b/w profiles. It'd be nice if u add it in future release. Anyway awesome kernel, using it for a week.

**Comment by krasCGQ** [comment]
Spectrum support has nothing to do with kernel source. Only report issues regarding kernel itself.
