### ISSUE TITLE
Colaboración para portear kernel al markw

### ISSUE THREAD

**Issue by GuardianXX** [KudProject/kernel_xiaomi_msm8953-3.18#3]
Hola amigo, he testeado tu kernel en el xiaomi redmi note 4 (mido) y me pareció muy estable y rápido, me gustaría colaborar contigo para que tu kernel este disponible para el xiaomi redmi 4 prime (markw), solo si me das permiso de trabajar contigo, solo le agregaré cambios del markw, no tocaré más del kernel amigo.
Igual paso por aquí para reportar un bug que he encontrado.
--No se puede instalar magisk, causa bootloop
Gracias por tu atención

**Comment by raphielscape** [comment]
@GuardianXX

**Comment by raphielscape** [comment]
@raphielscape Excuse me, what the duck

**Comment by raphielscape** [comment]
Excuse me, what the duck

**Comment by krasCGQ** [comment]
![](https://master.tus.io/files/41c287020466b59012147dd57c115d28)

I don't want to support more devices anymore. Anyway, for the last part: Magisk works.
