### ISSUE TITLE
Unsupported Android version error

### ISSUE THREAD

**Issue by Roker2** [KudProject/kernel_xiaomi_msm8953-3.18#5]
Hi! I download [this build](https://t.me/KudProjectCI/333) and got Unsupported Android version error. Can you fix it?

**Comment by krasCGQ** [comment]
Please don't report issues for builds posted on KudProjectCI Telegram channel. GitHub issues is for public releases.

And yes, AnyKernel hasn't been updated yet.

**Comment by krasCGQ** [comment]
https://t.me/KudProjectCI/335

Should be flashable on 10.
Also, Android 9 support is restricted to September 2019 ASB and newer starting from this build.

**Comment by krasCGQ** [comment]
@Roker2 sorry for pinging on GitHub.

Did you just send some amount of donation via PayPal? As PayPal flagged it as suspicious few minutes later...

I don't want to bring myself into trouble so I asked.
